dist: trusty
language: node_js
node_js:
  - '10'
script: npm run export
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: nextein
