# Site settings
title: elmasse
author: Maximiliano Fierro
disclaimer: "Any viewpoints and opinions expressed in this article are my own and do not, in any way, reflect those of my employer, my colleagues, or anyone else. I speak only for myself, not for them."
analytics: UA-58118079-1

twitter_username: elmasse
github_username:  elmasse
google_plus_username: MaximilianoFierro
linkedin_username: maximilianofierro

# Build settings
markdown: kramdown
permalink: none